# -- 기본 설정 -------------------------------------------------
title: Softwalk
subtitle: "시니어의 경험을 디지털로 연결하다"
description: "중장년 디지털 전환을 위한 소프트웨어 일자리 플랫폼"
url: "https://www.2hcube.com"
baseurl: "/softwalk"

# GitHub Pages remote theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air" # 깨끗한 디자인

# 빌드 설정
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 언어 설정
locale: "ko-KR"

markdown: kramdown
highlighter: rouge

# Collections (Scraps 포스팅 용)
collections:
  scraps:
    output: true
    permalink: /scraps/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false

# 상단 메뉴 (navigation.yml 연결)
site:
  navigation: main

# 하단 문구
footer_content: "This page was generated by [GitHub Pages](https://pages.github.com/)."
gh_edit_link: false
