# -- 기본 설정 -------------------------------------------------
title: Softwalk
subtitle: "시니어의 경험을 디지털로 연결하다"
description: "중장년 디지털 전환을 위한 소프트웨어 일자리 플랫폼"
url: "https://www.2hcube.com"
baseurl: "/softwalk"

# 테마 설정
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

# 빌드 설정 (최대한 단순하게)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed

# 언어 설정
locale: "ko-KR"

collections:
  scraps:
    output: true
    permalink: /scraps/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: ""
    values:
      layout: single

# 상단 메뉴 (navigation.yml 연결)
site:
  navigation: main

gh_edit_link: false
